service:
  name: podcast-hosting-app

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    JWKS_URL: https://dev-rjulv14u.auth0.com/.well-known/jwks.json

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          cors: true
          authorizer: Auth
